import type {
  ActivityItem,
  DataItem,
  Project,
  Report,
  SelectionSet,
  SourceConfig,
  SourceRun,
  UploadedFile,
} from "./types";
import { makeSelectionSet } from "./selection";

const now = Date.now();
const h = 60 * 60 * 1000;
const d = 24 * h;

export const seedProjects: Project[] = [
  {
    id: "china-auto-talent",
    name: "China Automotive Talent Insight",
    industry: "Automotive",
    region: "China",
    tags: ["Automotive", "China"],
    createdAt: now - 8 * d,
    updatedAt: now - 2 * h,
  },
  {
    id: "semiconductor-hiring",
    name: "Semiconductor Hiring Trends",
    industry: "Semiconductor",
    region: "APAC",
    tags: ["Semiconductor", "APAC"],
    createdAt: now - 16 * d,
    updatedAt: now - d,
  },
];

export const seedSources: SourceConfig[] = [
  {
    id: "src-careers",
    projectId: "china-auto-talent",
    type: "career_site",
    displayName: "Company Career Sites",
    description: "Collect job openings from company recruitment websites.",
    enabled: true,
    lastRunId: "RUN-20260716-001",
    config: { companies: ["Bosch", "Continental", "ZF", "BorgWarner", "NVIDIA"] },
  },
  {
    id: "src-liepin",
    projectId: "china-auto-talent",
    type: "liepin",
    displayName: "Liepin",
    description: "Collect public job listings from Liepin using a saved browser session.",
    enabled: false,
    lastRunId: "RUN-20260715-002",
    config: { keywords: ["ADAS", "EV controls", "automotive software"] },
  },
  {
    id: "src-tavily",
    projectId: "china-auto-talent",
    type: "tavily",
    displayName: "Tavily Search",
    description: "Search industry news, company activity, hiring trends, and market signals.",
    enabled: true,
    lastRunId: "RUN-20260714-001",
    config: { topics: ["ADAS hiring China", "automotive suppliers software talent"] },
  },
  {
    id: "src-url",
    projectId: "china-auto-talent",
    type: "url_import",
    displayName: "Imported URLs",
    description: "Import individual articles, company pages, and research notes from URLs.",
    enabled: true,
    config: { urls: ["https://example.com/market-note"] },
  },
  {
    id: "src-upload",
    projectId: "china-auto-talent",
    type: "upload",
    displayName: "Uploaded Files",
    description: "Internal files added to this project.",
    enabled: true,
    config: {},
  },
];

export const seedRuns: SourceRun[] = [
  {
    id: "RUN-20260716-001",
    projectId: "china-auto-talent",
    sourceIds: ["src-careers", "src-tavily"],
    status: "running",
    progress: 68,
    startedAt: now - 12 * 60 * 1000,
    recordsCreated: 357,
    warnings: [],
    log: [
      "Career Sites completed 5 / 5 companies.",
      "Tavily search is processing query 8 / 12.",
      "Current: Extracting Continental job details.",
    ],
  },
  {
    id: "RUN-20260715-003",
    projectId: "china-auto-talent",
    sourceIds: ["src-careers"],
    status: "completed",
    progress: 100,
    startedAt: now - d,
    endedAt: now - d + 263_000,
    recordsCreated: 312,
    warnings: [],
    log: ["Career site collection completed."],
  },
  {
    id: "RUN-20260715-002",
    projectId: "china-auto-talent",
    sourceIds: ["src-liepin"],
    status: "completed_with_warnings",
    progress: 100,
    startedAt: now - d - h,
    endedAt: now - d - h + 131_000,
    recordsCreated: 98,
    warnings: ["Two result pages required manual verification."],
    log: ["Liepin collection completed with warnings."],
  },
  {
    id: "RUN-20260712-002",
    projectId: "china-auto-talent",
    sourceIds: ["src-careers"],
    status: "failed",
    progress: 32,
    startedAt: now - 4 * d,
    endedAt: now - 4 * d + 62_000,
    recordsCreated: 0,
    warnings: ["One career site blocked automated access."],
    log: ["Collection stopped before record extraction."],
  },
];

const jobs: DataItem[] = [
  ["di-job-1", "Computer Vision Engineer", "ZF", "Shanghai", "Perception", "C++", "Lead perception software development for ADAS camera modules."],
  ["di-job-2", "HR Business Partner", "Continental", "Beijing", "People", "HRBP", "Partner with engineering leaders on hiring and workforce planning."],
  ["di-job-3", "Embedded Developer", "Continental", "Suzhou", "Embedded", "AUTOSAR", "Develop AUTOSAR components for electrified powertrain platforms."],
  ["di-job-4", "Senior Controls Engineer", "BorgWarner", "Nanjing", "Controls", "MATLAB", "Design control algorithms for inverter and motor systems."],
  ["di-job-5", "ADAS Software Engineer", "Bosch", "Shanghai", "Software", "AUTOSAR", "Lead development of ADAS perception modules using camera and radar data."],
  ["di-job-6", "Product Manager - EV", "BorgWarner", "Shanghai", "Product", "EV", "Coordinate regional product requirements for electric vehicle programs."],
  ["di-job-7", "ML Infrastructure Lead", "NVIDIA", "Shanghai", "AI Platform", "Python", "Build model training infrastructure for automotive AI workloads."],
  ["di-job-8", "AI Platform Engineer", "Bosch", "Wuxi", "AI Platform", "Linux", "Support internal AI tooling for driver assistance engineering teams."],
].map(([id, title, company, location, fn, skill, summary], index) => ({
  id,
  projectId: "china-auto-talent",
  sourceId: "src-careers",
  kind: "job" as const,
  title,
  summary,
  fields: {
    company,
    location,
    function: fn,
    primarySkill: skill,
    posted: `2026-07-${String(8 + index).padStart(2, "0")}`,
  },
  rawText: `${title}\n${company} - ${location}\n${summary}\nSkills: ${skill}, C++, Python, Linux`,
  url: `https://${company.toLowerCase().replace(/\s+/g, "")}.com/careers`,
  createdAt: now - 2 * h + index * 1000,
}));

export const seedDataItems: DataItem[] = [
  ...jobs,
  {
    id: "di-news-1",
    projectId: "china-auto-talent",
    sourceId: "src-tavily",
    kind: "news",
    title: "Automotive suppliers expand software teams in China",
    summary: "Recent hiring signals point to stronger demand for ADAS and electrification software talent.",
    fields: { publisher: "Industry Daily", company: "Multiple", topic: "Hiring" },
    rawText: "Automotive suppliers are expanding software hiring in Shanghai, Suzhou, and Wuxi.",
    url: "https://example.com/auto-software-hiring",
    createdAt: now - 2 * h,
  },
  {
    id: "di-news-2",
    projectId: "china-auto-talent",
    sourceId: "src-tavily",
    kind: "news",
    title: "ADAS role demand concentrates around perception and controls",
    summary: "Search results indicate demand clusters in perception, embedded controls, and AI infrastructure.",
    fields: { publisher: "Mobility Signals", topic: "ADAS" },
    rawText: "Role demand remains concentrated in perception, controls, and infrastructure.",
    url: "https://example.com/adas-demand",
    createdAt: now - 2 * h,
  },
  {
    id: "di-sheet-1",
    projectId: "china-auto-talent",
    sourceId: "src-upload",
    kind: "sheet_row",
    title: "Internal hiring benchmark row",
    summary: "Internal benchmark: Bosch 87 roles, Continental 63 roles, ZF 31 roles.",
    fields: { sheet: "Benchmark", Bosch: 87, Continental: 63, ZF: 31 },
    rawText: "Company,Bosch,Continental,ZF\nTotal Roles,87,63,31",
    fileRef: "file-hiring-xlsx",
    createdAt: now - 2 * h,
  },
  {
    id: "di-pdf-1",
    projectId: "china-auto-talent",
    sourceId: "src-upload",
    kind: "pdf_page",
    title: "Automotive Market Report.pdf - page 14",
    summary: "Market report page describing ADAS investment and China supplier localization.",
    fields: { pages: 86, page: 14 },
    rawText: "ADAS investment in China remains a priority for global suppliers as localization accelerates.",
    fileRef: "file-market-pdf",
    createdAt: now - 2 * h,
  },
  {
    id: "di-md-1",
    projectId: "china-auto-talent",
    sourceId: "src-upload",
    kind: "markdown",
    title: "Industry Notes.md",
    summary: "Analyst notes on talent demand, supplier priorities, and report framing.",
    fields: { author: "Research Team" },
    rawText: "Focus report narrative on competitor hiring comparison, skill demand, and geographic distribution.",
    fileRef: "file-notes-md",
    createdAt: now - 3 * h,
  },
  {
    id: "di-image-1",
    projectId: "china-auto-talent",
    sourceId: "src-upload",
    kind: "image",
    title: "Market Overview.png",
    summary: "Image asset for market overview slide.",
    fields: { width: 1600, height: 900 },
    rawText: "Image asset: Market Overview.png",
    fileRef: "file-market-png",
    createdAt: now - d,
  },
];

export const seedUploadedFiles: UploadedFile[] = [
  {
    id: "file-hiring-xlsx",
    projectId: "china-auto-talent",
    name: "Internal Hiring Data.xlsx",
    mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    size: 2_400_000,
    status: "ready",
    parsedItemIds: ["di-sheet-1"],
    uploadedAt: now - 2 * h,
  },
  {
    id: "file-market-pdf",
    projectId: "china-auto-talent",
    name: "Automotive Market Report.pdf",
    mimeType: "application/pdf",
    size: 8_100_000,
    status: "parsing",
    parsedItemIds: ["di-pdf-1"],
    uploadedAt: now - 2 * h,
  },
  {
    id: "file-notes-md",
    projectId: "china-auto-talent",
    name: "Industry Notes.md",
    mimeType: "text/markdown",
    size: 12_000,
    status: "ready",
    parsedItemIds: ["di-md-1"],
    uploadedAt: now - 3 * h,
  },
  {
    id: "file-market-png",
    projectId: "china-auto-talent",
    name: "Market Overview.png",
    mimeType: "image/png",
    size: 1_800_000,
    status: "ready",
    parsedItemIds: ["di-image-1"],
    uploadedAt: now - d,
  },
];

const selectedIds = [
  "di-job-3",
  "di-job-4",
  "di-job-5",
  "di-job-8",
  "di-news-1",
  "di-news-2",
  "di-sheet-1",
  "di-pdf-1",
  "di-image-1",
];

export const seedSelections: SelectionSet[] = [
  makeSelectionSet("china-auto-talent", selectedIds, seedDataItems),
  makeSelectionSet("semiconductor-hiring", [], []),
];

const reportHtml = `<!DOCTYPE html><html><head><title>China Automotive Hiring Comparison</title><style>body{font-family:Inter,Arial,sans-serif;color:#1f2937;margin:0;background:#f8fafc}.page{max-width:820px;margin:32px auto;background:white;padding:42px;border:1px solid #d9dee7}.kpis{display:flex;gap:16px}.kpi{border:1px solid #d9dee7;padding:18px;flex:1}.section{border-top:1px solid #e5e7eb;margin-top:28px;padding-top:24px}table{width:100%;border-collapse:collapse}td,th{border:1px solid #e5e7eb;padding:10px;text-align:left}</style></head><body><main class="page"><h1>China Automotive Hiring Comparison</h1><p>Automotive · China · Generated July 17, 2026 · 210 job records · 12 news articles</p><div class="kpis"><div class="kpi"><strong>210</strong><br/>Jobs Analyzed</div><div class="kpi"><strong>5</strong><br/>Companies Tracked</div><div class="kpi"><strong>+18%</strong><br/>YoY Hiring Growth</div></div><section class="section"><h2>Hiring Activity by Company</h2><table><thead><tr><th>Company</th><th>Total Roles</th><th>Engineering</th></tr></thead><tbody><tr><td>Bosch</td><td>87</td><td>74</td></tr><tr><td>Continental</td><td>63</td><td>51</td></tr><tr><td>ZF</td><td>31</td><td>25</td></tr><tr><td>BorgWarner</td><td>18</td><td>12</td></tr><tr><td>NVIDIA</td><td>11</td><td>11</td></tr></tbody></table></section><section class="section"><h2>Top Skills in Demand</h2><p>ADAS, AUTOSAR, C++, Python, Linux, and CAN Bus appear most frequently in selected job records.</p></section></main></body></html>`;

export const seedReports: Report[] = [
  {
    id: "report-hiring-comparison",
    projectId: "china-auto-talent",
    name: "China Automotive Hiring Comparison",
    templateId: "competitor-hiring-comparison",
    audience: "HR leadership",
    language: "English",
    goal: "Compare competitor hiring activity and skill demand.",
    status: "ready",
    html: reportHtml,
    insightIds: ["metric-job-volume", "chart-company-comparison", "table-function-demand"],
    selectedItemIds: selectedIds,
    createdAt: now - 2 * h,
    updatedAt: now - 2 * h,
    sections: [
      {
        id: "sec-exec",
        title: "Executive Summary",
        html: "<h2>Executive Summary</h2><p>Automotive software hiring is concentrated around ADAS, embedded controls, and AI platform roles.</p>",
        sourceItemIds: selectedIds.slice(0, 5),
        comments: [],
        order: 0,
      },
      {
        id: "sec-company",
        title: "Company Comparison",
        html: "<h2>Company Comparison</h2><p>Bosch records the highest job volume, followed by Continental and ZF.</p>",
        sourceItemIds: ["di-job-3", "di-job-5", "di-sheet-1"],
        comments: [
          {
            id: "comment-1",
            sectionId: "sec-company",
            text: "Add a short note on engineering share.",
            resolved: false,
            createdAt: now - h,
          },
        ],
        order: 1,
      },
      {
        id: "sec-skills",
        title: "Skill Demand",
        html: "<h2>Skill Demand</h2><p>ADAS, AUTOSAR, C++, Python, ROS2, Linux, and CAN Bus are frequent requirements.</p>",
        sourceItemIds: ["di-job-4", "di-job-5", "di-job-8"],
        comments: [],
        order: 2,
      },
    ],
  },
  {
    id: "report-adas-brief",
    projectId: "china-auto-talent",
    name: "ADAS Talent Landscape Brief",
    templateId: "executive-industry-brief",
    audience: "Executive team",
    language: "English",
    goal: "Summarize ADAS hiring trends.",
    status: "ready",
    html: reportHtml,
    sections: [],
    insightIds: [],
    selectedItemIds: selectedIds.slice(0, 5),
    createdAt: now - d,
    updatedAt: now - d,
  },
  {
    id: "report-bosch-dashboard",
    projectId: "china-auto-talent",
    name: "Bosch China HR Dashboard",
    templateId: "talent-market-dashboard",
    audience: "HR strategy",
    language: "Chinese",
    goal: "Track Bosch China talent market signals.",
    status: "draft",
    html: "",
    sections: [],
    insightIds: [],
    selectedItemIds: selectedIds.slice(0, 4),
    createdAt: now - 3 * d,
    updatedAt: now - 3 * d,
  },
];

export const seedActivity: ActivityItem[] = [
  {
    id: "act-1",
    projectId: "china-auto-talent",
    label: "Bosch career site collection completed",
    tone: "success",
    createdAt: now - 2 * h,
  },
  {
    id: "act-2",
    projectId: "china-auto-talent",
    label: "94 jobs extracted from Continental",
    tone: "success",
    createdAt: now - 2 * h,
  },
  {
    id: "act-3",
    projectId: "china-auto-talent",
    label: "Tavily search: 44 news records collected",
    tone: "success",
    createdAt: now - 2 * h,
  },
  {
    id: "act-4",
    projectId: "china-auto-talent",
    label: 'Report "China Automotive Hiring Comparison" generated',
    tone: "info",
    createdAt: now - d,
  },
  {
    id: "act-5",
    projectId: "china-auto-talent",
    label: "Liepin collection completed with 2 warnings",
    tone: "warning",
    createdAt: now - d,
  },
];
